### ISSUE TITLE
Getting 500 error when deployed to vercel

### ISSUE THREAD

**Issue by vasantharaja200295** [mitchmac/ServerlessWP#67]
Hello, I'm facing issues when I try to deploy serverlessWP to vercel, since planetscale has removed the free tier I am trying to use cockroach db for this. the issues im facing are im getting a 500 error when i try to open the preview link from vercel. I have attached the logs of the issue please help me on this.

Thank you.

**Logs:**
[logs_result.json](https://github.com/user-attachments/files/16404244/logs_result.json)

**Comment by sleakchat** [comment]
@vasantharaja200295 have you managed to fix this? I'm encountering the same error

@mitchmac maybe you know?

**Comment by vasantharaja200295** [comment]
> @vasantharaja200295 have you managed to fix this? I'm encountering the same error
> 
> @mitchmac maybe you know?

No man i can't find a way to fix it

**Comment by awan-gh** [comment]
> > @vasantharaja200295 have you managed to fix this? I'm encountering the same error
> > @mitchmac maybe you know?
> 
> No man i can't find a way to fix it

I have a working personal blog, deployed on Vercel. Use Aiven.io for the database, don't forget to set the region close to your vercel region.

**Comment by aldosch** [comment]
I fixed this by using Node.js v18.x instead of the default v20.x and then redeploying.

- Docs: [Setting the Node.js version in project settings](https://vercel.com/docs/functions/runtimes/node-js/node-js-versions#setting-the-node.js-version-in-project-settings)
- Related issue: [Issue with Deployment on Vercel and Netlify Due to Incompatibility with Node.js Version 20.x #64](https://github.com/mitchmac/ServerlessWP/issues/64)

**Comment by aldosch** [comment]
Created pull request #73 to solve this

**Comment by mitchmac** [comment]
Thank you @aldosch -- I'll try to find time to update for node 20 compatibility one of these days!
